-- ============================================================================
-- Migration: 127_ap2_ipv6_deep.sql
-- Description: Massive IPv6-Vertiefung — Adresstypen, SLAAC/NDP,
--              Privacy Extensions, DHCPv6, Dual-Stack, ip-address-Output,
--              AP1-2026-Muster, Subnetting-Hierarchie, Migration.
-- Version: 1.0.0
-- Date: 2026-04-18
-- ============================================================================

WITH topic_lookup AS (SELECT slug, topic_id FROM assessments.ap2_topics WHERE slug = 'ipv6-subnetting')
INSERT INTO assessments.ap2_learning_items
    (topic_id, item_type, prompt, model_answer, points, source_exam, difficulty, estimated_time_sec)
SELECT t.topic_id, v.item_type, v.prompt, v.model_answer, v.points::numeric, v.source_exam, v.difficulty::int, v.estimated_time_sec::int
FROM topic_lookup t, (VALUES

-- ============================================================
-- BLURTS (3 weitere)
-- ============================================================

('blurt',
 'Schreibe alles was du über IPv6-Adresstypen weißt: Global Unicast, Link-Local, Unique Local, Multicast, Anycast, Loopback, Unspezifiziert. Nenne Präfixe, Zwecke, Beispiele.',
 'IPv6-Adresstypen:\n\n1. Global Unicast (GUA): Präfix 2000::/3 (also 2000 - 3FFF). Weltweit eindeutig + routbar. Vom Provider zugewiesen. Beispiel: 2001:db8:ea:1::1 (2001:db8::/32 ist für Dokumentation reserviert).\n\n2. Link-Local (LLA): Präfix fe80::/10 (faktisch fe80::/64). Jedes Interface bekommt AUTOMATISCH eine. Nur auf dem lokalen Segment gültig, NICHT routbar. Genutzt für NDP, Router-Kommunikation. Beispiel: fe80::1a:2bff:fe3c:4d5e.\n\n3. Unique Local (ULA): Präfix fc00::/7 (praktisch fd00::/8 für privat gewählte). Wie IPv4-Privat (10.0.0.0/8). Nicht routbar im Internet, aber innerhalb Organisation. Ersatz für Site-Local (deprecated).\n\n4. Multicast: Präfix ff00::/8. Ersetzt Broadcast von IPv4 (IPv6 hat KEIN Broadcast mehr). Wichtige Multicast-Adressen:\n   - ff02::1 — alle Knoten im Link (all-nodes).\n   - ff02::2 — alle Router im Link (all-routers).\n   - ff02::1:ffxx:xxxx — Solicited-Node (für NDP Neighbor Solicitation).\n\n5. Anycast: 1-zu-nächster (eine Gruppe, Paket geht zum topologisch nächsten Mitglied). Teilt Adressraum mit Unicast. Für DNS-Root-Server genutzt.\n\n6. Loopback: ::1 (entspricht 127.0.0.1 in IPv4).\n\n7. Unspezifiziert: :: (alle Null, entspricht 0.0.0.0). Verwendet vor der Adressvergabe als Quell-Adresse.\n\nKEIN Broadcast mehr in IPv6 — Multicast ersetzt es.',
 12, 'ki-generated', 4, 540),

('blurt',
 'Schreibe alles was du über NDP (Neighbor Discovery Protocol) und SLAAC (Stateless Address Autoconfiguration) weißt. Wie werden die Nachrichten genutzt, welche ICMPv6-Typen?',
 'NDP (RFC 4861) — Ersetzt in IPv6 das ARP-Protokoll. Basiert auf ICMPv6-Nachrichten + Multicast.\n\n5 ICMPv6-Nachrichtentypen:\n1. Router Solicitation (RS, Typ 133): Host fragt "Wer ist Router?" Bei Bootup gesendet an ff02::2.\n2. Router Advertisement (RA, Typ 134): Router antwortet mit Präfix, Default-Route, DNS-Info, Lifetime. Periodisch + auf Anfrage. Enthält M-Flag (DHCPv6 für Adresse) + O-Flag (DHCPv6 für Optionen wie DNS).\n3. Neighbor Solicitation (NS, Typ 135): Ersatz für ARP Request. "Wer hat IP X?" Gesendet an Solicited-Node Multicast.\n4. Neighbor Advertisement (NA, Typ 136): Ersatz für ARP Reply. Wenn Empfänger angesprochen.\n5. Redirect (Typ 137): Router sagt "Besseren Router nutzen".\n\nSLAAC-Ablauf (RFC 4862):\n1. Host generiert Link-Local (fe80::/64 + EUI-64 aus MAC oder Random).\n2. DAD (Duplicate Address Detection): Host schickt NS für seine eigene Link-Local an Solicited-Node-Multicast. Falls jemand antwortet → Konflikt, Host stoppt.\n3. Host schickt Router Solicitation an ff02::2.\n4. Router antwortet mit Router Advertisement (Präfix, Router-IP).\n5. Host bildet globale Adresse: empfangenes Präfix + eigene Interface-ID.\n6. DAD auch für globale Adresse.\n7. Default-Gateway = Router-LLA aus RA.\n\nVorteil: OHNE DHCP-Server. Nachteil: Server bekommen zufällige Adressen — oft DHCPv6 STATEFUL für Server, SLAAC für Clients.',
 13, 'ki-generated', 5, 540),

('blurt',
 'Schreibe alles über IPv6-Subnetting: Warum /64 Standard, Hierarchie Provider → Site → Subnet, Präfix-Delegation, Berechnung Anzahl Subnetze, Router-on-a-Stick mit IPv6.',
 'IPv6-Subnetting:\n\nStandard = /64 für Endnetze (LAN, WLAN, VLAN). Gründe:\n- EUI-64 braucht 64 Bit Interface-ID (aus 48-Bit-MAC + "FFFE").\n- SLAAC setzt /64 voraus.\n- /64 hat 2^64 = 1,8 × 10^19 Adressen — "unlimitiert".\n\nHierarchie (typisch):\n- Provider-Zuweisung: /32 oder /40 (Internet Assigned Numbers Authority → Provider).\n- Kunde/Site-Zuweisung: /48 oder /56 (Provider → Firma).\n- Innerhalb Site: /64 pro Subnetz (Firma → VLAN).\n\nBeispiel Firma mit /56-Zuweisung 2001:db8:ea:2300::/56:\n- 56 → 64 = 8 Bit für Subnetze → 2^8 = 256 mögliche /64-Subnetze.\n- VLAN 10: 2001:db8:ea:2310::/64\n- VLAN 20: 2001:db8:ea:2320::/64\n- VLAN 30: 2001:db8:ea:2330::/64\n\nFormel: Anzahl Subnetze = 2^(Ziel-Präfix − Start-Präfix). Bei /48 → /64: 2^16 = 65.536 Subnetze.\n\nPräfix-Delegation (DHCPv6-PD):\nRouter bekommt /56 vom Provider-DHCPv6 → teilt in /64 für interne Netze auf. Dynamisch — bei Provider-Wechsel ändert sich Präfix automatisch. Genutzt bei Kabel-/Glasfaser-Routern.\n\nRouter-on-a-Stick (IPv6 auf Trunk): Subinterfaces pro VLAN mit eigenem /64. Beispiel: eth0.10 = 2001:db8:ea:2310::1/64, eth0.20 = 2001:db8:ea:2320::1/64.\n\nKEINE Host-Bit-Abzüge wie IPv4: Alle 2^64 Adressen eines /64 sind nutzbar (kein Broadcast). Einzige Ausnahme: Subnet-Anycast (erste Adresse :: ) und einige reservierte EUI-64-Adressen.',
 12, 'ki-generated', 5, 540),

-- ============================================================
-- CUED (8 zusätzliche)
-- ============================================================

('cued',
 'ip addr show enp0s3 zeigt:\ninet6 2a02:8030:42:0:a00:27ff:fe1e:9403/64 scope global\ninet6 fe80::a00:27ff:fe1e:9403/64 scope link\n\nErläutere beide Adressen (Typ, Zweck, Reichweite).',
 'Adresse 1: 2a02:8030:42:0:a00:27ff:fe1e:9403/64\n- Typ: Global Unicast (Präfix 2000::/3 — 2a02... liegt drin).\n- Zweck: weltweit routbar, Internet-Kommunikation.\n- Reichweite: "scope global" = unbegrenzt.\n- Interface-ID "a00:27ff:fe1e:9403" ist EUI-64 — man sieht das "FF:FE" in der Mitte (27ff:fe1e). Die ursprüngliche MAC war vermutlich 08:00:27:1e:94:03 (typisch VirtualBox/VMware), das 7. Bit wurde geflippt → 0a:00:27:1e:94:03.\n\nAdresse 2: fe80::a00:27ff:fe1e:9403/64\n- Typ: Link-Local (Präfix fe80::/10).\n- Zweck: Kommunikation auf dem lokalen Segment (Neighbor Discovery, Router-Kommunikation).\n- Reichweite: "scope link" = nur auf diesem Interface-Netz.\n- Wird AUTOMATISCH beim Interface-Up erstellt, kann nicht deaktiviert werden.',
 4, 'W2324-PB3-3.4.2', 3, 240),

('cued',
 'Was ist der Unterschied zwischen SLAAC, DHCPv6 Stateless und DHCPv6 Stateful? Wann nutzt man was?',
 'SLAAC (Stateless Address Autoconfig):\n- Host generiert Adresse selbst aus Router-Advertisement-Präfix + EUI-64/Random.\n- KEIN DHCP-Server nötig.\n- Keine DNS-Info (nur via RA, wenn Router sie mitschickt — RDNSS-Option, RFC 6106).\n- Nutzung: typisch für Client-Netze wo IP dynamisch passen darf.\n\nDHCPv6 Stateless:\n- SLAAC generiert Adresse, ABER DHCPv6-Server liefert ZUSATZ-Infos (DNS, NTP, Domain).\n- Router Advertisement setzt O-Flag (Other).\n- Nutzung: SLAAC für Adressen, DHCPv6 nur für DNS etc.\n\nDHCPv6 Stateful:\n- DHCPv6-Server weist komplette Adresse zu (wie IPv4-DHCP).\n- Router Advertisement setzt M-Flag (Managed).\n- Server führt Buch (Leases).\n- Nutzung: Server mit fester Adresse, Corporate-Umgebung mit zentraler Kontrolle.\n\nKombination: M-Flag UND O-Flag steuern das Verhalten. M=1 → DHCPv6-Stateful. M=0, O=1 → SLAAC + DHCPv6-Stateless.',
 4, 'ki-generated', 5, 240),

('cued',
 'Wie funktioniert Duplicate Address Detection (DAD) in IPv6 und welche Rolle spielt dabei die Solicited-Node-Multicast-Adresse?',
 'DAD (Duplicate Address Detection, RFC 4862):\n\nNach Adress-Konfiguration prüft der Host OB die Adresse schon im Netz vergeben ist.\n\nAblauf:\n1. Host bildet Adresse (Link-Local oder Global).\n2. Host berechnet Solicited-Node-Multicast für diese Adresse:\n   ff02::1:ff + letzte 24 Bit der Ziel-Adresse.\n   Beispiel: Adresse fe80::1a:2b3c:4d5e:6f70 → Solicited-Node = ff02::1:ff5e:6f70.\n3. Host schickt Neighbor Solicitation an diese Multicast-Adresse (Quelle = ::, Unspezifiziert).\n4. Wenn jemand die Adresse bereits hat → er antwortet mit NA (zu ff02::1, all-nodes).\n5. Wenn nach ~1 Sekunde keine Antwort → Adresse ist frei, Host aktiviert sie.\n\nSolicited-Node-Multicast ist optimiert: statt an alle im Netz (ff02::1) zu fragen, fragt man nur eine spezifische Multicast-Gruppe. Jeder Host abonniert automatisch Solicited-Node für jede seiner Adressen — weniger "Lärm" im Netz.',
 3, 'ki-generated', 5, 240),

('cued',
 'Was sind Privacy Extensions (RFC 4941 / 8981) in IPv6 und warum wurden sie eingeführt?',
 'Privacy Extensions / Temporary Addresses:\n\nProblem: EUI-64 basiert auf der MAC-Adresse — diese ist WELTWEIT eindeutig und ändert sich nie. Ein Webserver sieht also in der globalen IPv6 die MAC des Clients → Tracking über Netzwerke hinweg möglich.\n\nLösung RFC 4941 / 8981: Host generiert zusätzliche temporäre Adresse mit zufälliger 64-Bit-Interface-ID.\n- Für AUSGEHENDE Verbindungen wird die temporäre Adresse genutzt.\n- Für eingehende Server-Dienste weiterhin die EUI-64-Adresse.\n- Temporäre Adresse rotiert typisch täglich (Lifetime konfigurierbar).\n- Alte Adressen bleiben kurzzeitig gültig für laufende Verbindungen.\n\nHeute Standard in Windows, macOS, iOS, Android. Linux per sysctl aktivierbar (net.ipv6.conf.all.use_tempaddr=2).',
 3, 'ki-generated', 4, 180),

('cued',
 'Firma erhält vom Provider 2001:db8:ea:2300::/56. Sie will 8 VLANs. Gib die Subnetze an und erkläre wie viele Subnetze insgesamt möglich wären.',
 'Vom /56 → /64 sind 8 Bit für Subnetting frei → maximal 2^8 = 256 /64-Subnetze.\n\n8 VLAN-Subnetze (Hex-Inkrement im 4. Block):\nVLAN 10: 2001:db8:ea:2310::/64\nVLAN 20: 2001:db8:ea:2320::/64\nVLAN 30: 2001:db8:ea:2330::/64\nVLAN 40: 2001:db8:ea:2340::/64\nVLAN 50: 2001:db8:ea:2350::/64\nVLAN 60: 2001:db8:ea:2360::/64\nVLAN 70: 2001:db8:ea:2370::/64\nVLAN 80: 2001:db8:ea:2380::/64\n\n(Man könnte auch inkrementell zählen: ::2300, ::2301, ::2302, ... — die Zahl "10 20 30" wurden hier bewusst gewählt für Parallelität zu VLAN-Nummern.)\n\nJedes /64-Subnetz hat 2^64 Adressen (1,8 × 10^19). Pro VLAN 248 noch 248 weitere Subnetze frei — Platz ist de facto unbegrenzt.',
 3, 'ki-generated', 3, 180),

('cued',
 'Was ist Dual-Stack und welche Alternativen gibt es für den IPv4→IPv6-Übergang?',
 'Dual-Stack: Jedes Gerät hat sowohl IPv4 als auch IPv6 parallel aktiviert. Anwendungen wählen Protokoll (meist IPv6 bevorzugt, Fallback IPv4). Beste Lösung — beide funktionieren. Standard in modernen Netzen. Nachteil: doppelte Administration.\n\nAlternativen (für schrittweise Migration oder Problemfälle):\n\n1. Tunneling (v6-Pakete in v4-Pakete kapseln):\n- 6to4: automatisches Tunneling mit 2002::/16 Präfix aus v4-Adresse abgeleitet. Deprecated.\n- Teredo: NAT-Traversal für v6 in v4 UDP. Microsoft, heute kaum genutzt.\n- ISATAP: Intra-Site. Windows-spezifisch, alt.\n- 6in4 (Protokoll 41): manuelle statische Tunnel, Hurricane Electric.\n\n2. Translation:\n- NAT64 + DNS64: Clients mit nur v6 erreichen v4-Ressourcen über Translator. Beliebt bei Mobilfunk-Carriern.\n- NAT46: umgekehrt, selten.\n- 464XLAT: Mobilfunk-Standard — Client hat nur v6, Apps sehen v4 durch lokalen Translator.\n\nEmpfehlung heute: DUAL-STACK beim Aufbau, NAT64/DNS64 wenn v6-only gefahren werden soll.',
 4, 'ki-generated', 5, 300),

('cued',
 'MAC-Adresse fa:16:3e:9a:bc:de. Bilde die EUI-64 Interface-ID Schritt-für-Schritt.',
 'Schritt 1: MAC in 2 Hälften teilen:\nfa:16:3e | 9a:bc:de\n\nSchritt 2: FFFE in die Mitte einfügen:\nfa:16:3e:ff:fe:9a:bc:de\n\nSchritt 3: 7. Bit des ersten Oktetts flippen (Universal/Local-Bit):\nfa = 1111 1010\nBit 7 umkehren (zählend von links, 0-indexed Bit 1) = Bit an Position 2 von rechts in der zweiten Nibble... einfacher: fa XOR 02 = f8.\nfa → f8\n\nResultat: Interface-ID = f816:3eff:fe9a:bcde\n\nMit Link-Local-Präfix: fe80::f816:3eff:fe9a:bcde\nMit Global-Präfix 2001:db8:ea:1::/64: 2001:db8:ea:1:f816:3eff:fe9a:bcde\n\n(Merkhilfe: "flippe das zweite Bit von rechts im ersten Byte" — fa = ...fa → ...f8, d0 → d2, 00 → 02.)',
 3, 'ki-generated', 4, 240),

('cued',
 'Was ersetzt in IPv6 die Funktion von ARP aus IPv4? Welche Schicht + welches Protokoll?',
 'NDP (Neighbor Discovery Protocol, RFC 4861) ersetzt ARP.\n\nSchicht: NDP nutzt ICMPv6 (Internet Control Message Protocol Version 6) — das sitzt auf Layer 3 (Netzwerk), obwohl ARP in IPv4 auf Layer 2/3-Grenze arbeitet. NDP ist also ein echtes Layer-3-Protokoll.\n\nKern-Funktion (wie ARP): Link-Layer-Adresse (MAC) einer IPv6-Adresse erfragen.\n\nAblauf:\n1. Host will Paket an IPv6-Adresse X senden.\n2. Host schickt Neighbor Solicitation (ICMPv6 Typ 135) an Solicited-Node-Multicast-Adresse von X.\n3. Host mit Adresse X antwortet mit Neighbor Advertisement (Typ 136), enthält seine MAC.\n4. Anfragender Host cached die Antwort in Neighbor Cache (entspricht ARP-Cache).\n\nZusatz-Funktionen von NDP (mehr als ARP):\n- Router Discovery (Router finden).\n- Prefix Discovery (Präfix lernen).\n- Address Autoconfiguration (SLAAC).\n- Duplicate Address Detection.\n- Redirect-Funktion (besseren Router vorschlagen).',
 3, 'ki-generated', 4, 240),

-- ============================================================
-- APPLICATIONS (3 zusätzliche)
-- ============================================================

('application',
 'AP1-2026-Typ-Aufgabe: Provider gibt Präfix 2001:0db8:00ea:2300::/56. Der Internet-Router verwendet für das Admin-Netz das /64-Subnetz 2001:db8:ea:2301::/64, für das WLAN 2001:db8:ea:2302::/64. Der Admin-PC (PC-Nr AB.1001) soll manuell konfiguriert werden. Router-Interface-LLA: fe80::1, DNS-Server-LLA: fe80::d. Gib für den Admin-PC an: globale IPv6-Adresse mit Präfixlänge, Gateway, DNS — alle in Kurzform.',
 'Manuelle IPv6-Konfiguration Admin-PC:\n\nGlobale IPv6-Adresse:\n- Präfix: 2001:db8:ea:2301::/64 (Admin-Netz)\n- Interface-ID: Da PC-Nr "AB.1001" vorgegeben ist → Host-ID ::ab01 (oder ::ab:1001, je nach Interpretation; in typischen BW-Aufgaben ist "ab01" die kompakte Variante).\n→ Globale Adresse: 2001:db8:ea:2301::ab01/64\n\nGateway:\nDer Router ist am Admin-Netz mit fe80::1 erreichbar. Link-Local reicht für Gateway in IPv6 (üblich und empfohlen — macht Renumbering einfacher).\n→ Gateway: fe80::1/64 (oder eigentlich keine Präfixlänge, weil Link-Local per Definition /64 hat, aber in Prüfung oft angegeben)\n\nDNS-Server:\n- DNS: fe80::d/64 (Link-Local-Adresse des DNS-Servers)\n- Alternativ (bevorzugt für DNS): falls DNS auch globale Adresse hat, diese nutzen.\n\nKonfiguration (Windows) in kurzform:\nAdresse: 2001:db8:ea:2301::ab01\nPräfix: 64\nGateway: fe80::1\nDNS: fe80::d\n\nHinweis: In Prüfungen wird die Kurzform verlangt — führende Nullen weg (2001:0db8:00ea:2301:: → 2001:db8:ea:2301::), zusammenhängende Null-Blöcke durch :: (nur einmal) ersetzen.',
 8, 'AP1-2026-3.4', 5, 720),

('application',
 'Plane die komplette IPv6-Konfiguration für ein KMU mit 4 VLANs und Einsatz von SLAAC + DHCPv6-PD vom Provider. Folgende Anforderungen: 1) Server-VLAN mit festen Adressen (kein SLAAC), 2) Client-VLAN mit SLAAC + Privacy Extensions, 3) IoT-VLAN ohne Internet-Zugang, 4) Gäste-VLAN. Vom Provider: /56 via PD. Begründe jede Entscheidung.',
 'IPv6-Konfiguration KMU:\n\nPräfix-Delegation: Provider-Router erhält via DHCPv6-PD ein /56 (z.B. 2001:db8:ea:2300::/56). Dieses Präfix wird auf interne VLANs verteilt.\n\nVLAN-Zuweisung:\n- VLAN 10 Server:  2001:db8:ea:2310::/64 (fest)\n- VLAN 20 Client:  2001:db8:ea:2320::/64 (SLAAC)\n- VLAN 30 IoT:     fd00::1:30::/64 (ULA, nicht routbar!)\n- VLAN 40 Gäste:   2001:db8:ea:2340::/64 (SLAAC)\n\nBegründung + Konfiguration pro VLAN:\n\n1) SERVER-VLAN (10):\n- DHCPv6-Stateful (M-Flag=1 im RA) → Server bekommen feste Adressen vom DHCPv6-Server.\n- Beispiel: Webserver = 2001:db8:ea:2310::80, DB = 2001:db8:ea:2310::db, Mail = 2001:db8:ea:2310::25.\n- Begründung: Firewall-Regeln und DNS-Einträge verlangen stabile IPs.\n\n2) CLIENT-VLAN (20):\n- SLAAC (M=0, O=1) → Clients generieren Adressen via EUI-64 + Privacy Extensions.\n- DNS-Info via RDNSS-Option im RA (RFC 8106).\n- Begründung: zero-config, Datenschutz durch rotierende temporäre Adressen.\n\n3) IoT-VLAN (30):\n- ULA-Präfix fd00::1:30::/64 (keine globalen Adressen — IoT soll nicht direkt aus dem Internet erreichbar sein).\n- Alternative: globaler Präfix 2001:db8:ea:2330::/64, aber Firewall blockt eingehend.\n- SLAAC aktiv für IoT-Geräte (sie sprechen oft nicht DHCPv6).\n- Begründung: Security-Isolation, keine direkte Internet-Exposition.\n\n4) GÄSTE-VLAN (40):\n- SLAAC + Privacy Extensions.\n- Firewall: nur Internet, keine interne Netze.\n- Kurze Lease-Zeit (30 min).\n- Begründung: einfaches Setup für Gäste, isoliert von Interna.\n\nRouter-Konfiguration (Pseudo):\n- eth0.10: statisch 2001:db8:ea:2310::1/64, DHCPv6-Server aktiv.\n- eth0.20: statisch 2001:db8:ea:2320::1/64, RA mit Präfix + RDNSS.\n- eth0.30: statisch fd00::1:30::1/64, RA mit ULA-Präfix.\n- eth0.40: statisch 2001:db8:ea:2340::1/64, RA ohne default-route... Moment, defaultroute muss da sein sonst kein Internet. Lösung: Firewall filtert statt Router.\n\nFirewall-Regeln:\n- Server-VLAN → Internet ALLOW spezifische Ports.\n- Client-VLAN → Internet ALLOW, → Server ALLOW spezifisch.\n- IoT-VLAN → Internet DROP (außer NTP + Firmware-Updates).\n- Gäste-VLAN → Internet ALLOW, → alle anderen VLANs DROP.',
 12, 'ki-generated', 5, 1200),

('application',
 'Migrationsszenario: Bestehendes IPv4-Netz (192.168.0.0/16) soll auf Dual-Stack migriert werden. Netz hat 50 Mitarbeiter, 5 VLANs, Internet-Anschluss mit /56 IPv6-Präfix, DNS-Server, DHCP für v4. Beschreibe die 4 Migrationsschritte + welche Tests du nach jedem Schritt machst.',
 'IPv4 → Dual-Stack Migration in 4 Schritten:\n\nSCHRITT 1: Provider-seitige IPv6-Aktivierung\n- Provider liefert /56 via DHCPv6-PD.\n- Router aktiviert WAN-seitig IPv6.\n- Interne Netze noch komplett v4.\nTest: \n  ping6 -c 4 google.com vom Router.\n  ip -6 route show default (default route vorhanden?).\n\nSCHRITT 2: VLAN-Infrastruktur vorbereiten\n- Pro VLAN ein /64 aus dem /56 zuweisen.\n- Switch/Router-Interface bekommen IPv6-Adresse (GUA + LLA).\n- Router Advertisement mit Präfix pro VLAN aktivieren.\n- DHCPv6-Server für Server-VLAN, SLAAC für Clients.\n- KEIN Internet-Routing für Clients noch — nur interne Konnektivität.\nTest:\n  Auf jedem VLAN einen Test-Host: ping6 auf das Gateway.\n  Zwei Hosts im selben VLAN: ping6 untereinander.\n  Neighbor-Cache prüfen (ip -6 neigh show).\n\nSCHRITT 3: IPv6-Firewall-Regeln + DNS AAAA\n- Firewall-Regeln für IPv6 nachziehen (iptables6 / nftables).\n  WICHTIG: Regeln müssen ICMPv6 ERLAUBEN (sonst NDP kaputt!). Typen 133-137 zwingend.\n- Interner DNS: AAAA-Records für Server-Adressen hinzufügen.\n- Externe DNS-Auflösung: IPv6-fähige DNS-Server eintragen (2001:4860:4860::8888 = Google).\nTest:\n  nslookup -type=AAAA intranet.local — löst IPv6?\n  traceroute6 google.com — geht über Firewall durch?\n  nmap -6 interner Server — Firewall öffnet nur erwartete Ports?\n  curl -6 https://test.com — externer v6-Zugriff funktioniert?\n\nSCHRITT 4: Applikations-Tests + Monitoring\n- Anwendungen in Test-VLAN migrieren (Web, Mail, File).\n- Logging auf IPv6 aktivieren (Access-Logs auch v6-IPs).\n- Happy Eyeballs: Browser probieren v6 zuerst, fallen auf v4 zurück — Performance testen.\n- Monitoring: SNMP, nagios etc. auf v6 erweitern.\nTest:\n  curl -6 https://firmenserver.de vs curl -4.\n  Mail-Empfang mit v6-MX-Eintrag.\n  SMB/CIFS auf File-Server via v6.\n  Performance-Vergleich v4 vs v6 (iperf3 -6).\n\nNach Erfolg: IPv4 bleibt PARALLEL aktiv (Dual-Stack). Keine Abschaltung — sonst brechen ältere Geräte weg (Drucker, IoT).\n\nFallback-Plan: Bei Problemen pro VLAN IPv6 deaktivierbar durch Abschalten von RA und DHCPv6.',
 10, 'ki-generated', 5, 1500)

) AS v(item_type, prompt, model_answer, points, source_exam, difficulty, estimated_time_sec)
WHERE t.slug = 'ipv6-subnetting'
ON CONFLICT DO NOTHING;
