from app.setup.seeds.ui_schemas import SeedDataUISchemas, seed_learning_methods_ui_schemas, seed_system_features_ui_schemas
from app.setup.seeds.ui_schemas_part2 import get_learning_methods_schemas_group_b_c
from app.setup.seeds.ui_schemas_part3 import get_system_features_schemas
from app.setup.seeds.config_part2 import SeedDataConfigCategories, seed_categories
