"""
LernsystemX Admin Exam Models

Pydantic models for admin exam management operations:
- Admin exam list response
- Admin exam detail response
- Admin exam create request
- Admin exam update request
- Admin exam generate request (AI)
- Exam question models

Phase C1.3 - KI-Prüfungs-Generator
Based on Dok 04 (Kurs-Architektur.md) and Dok 09 (KI-Pipeline.md)
"""

from typing import Optional, List, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field, field_validator, ConfigDict

from app.domain.models.enums import ExamType, ExamStandard, QuestionType


class ExamQuestionResponse(BaseModel):
    """
    Single exam question response model

    Example:
        >>> question = ExamQuestionResponse(
        ...     question_id="uuid",
        ...     exam_id="uuid",
        ...     question_type="mcq",
        ...     question_text="Was ist das OSI-Modell?",
        ...     data={"options": [...], "correct": 1},
        ...     solution={"answer": "...", "explanation": "..."},
        ...     points=2
        ... )
    """
    question_id: str = Field(..., description="Question UUID")
    exam_id: str = Field(..., description="Exam UUID")
    question_type: QuestionType = Field(..., description="Type of question")
    question_text: str = Field(..., description="The question text")
    data: Dict[str, Any] = Field(default={}, description="Question-specific data (JSONB)")
    solution: Dict[str, Any] = Field(default={}, description="Solution data (JSONB)")
    points: int = Field(default=1, ge=1, le=100, description="Points for this question")
    order_index: int = Field(default=1, description="Question order")

    model_config = ConfigDict(from_attributes=True)


class ExamListItem(BaseModel):
    """
    Admin exam list item model

    Example:
        >>> exam = ExamListItem(
        ...     exam_id="uuid",
        ...     course_id="uuid",
        ...     exam_type="ai_simulation",
        ...     title="IHK FISI AP1 Simulation",
        ...     duration_minutes=90,
        ...     passing_score=50,
        ...     question_count=40,
        ...     generated_by_ai=True,
        ...     created_at=datetime.now()
        ... )
    """
    exam_id: str = Field(..., description="Exam UUID")
    course_id: str = Field(..., description="Course UUID")
    exam_type: ExamType = Field(..., description="Type of exam")
    title: str = Field(..., description="Exam title")
    description: Optional[str] = Field(None, description="Exam description")
    duration_minutes: int = Field(default=60, ge=1, description="Exam duration in minutes")
    passing_score: int = Field(default=50, ge=0, le=100, description="Passing score percentage")
    question_count: int = Field(default=0, description="Number of questions")
    generated_by_ai: bool = Field(default=False, description="Was generated by AI")
    published: bool = Field(default=False, description="Is exam published")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: Optional[datetime] = Field(None, description="Last update timestamp")

    model_config = ConfigDict(from_attributes=True)


class ExamDetailResponse(BaseModel):
    """
    Admin detailed exam model

    Example:
        >>> exam = ExamDetailResponse(
        ...     exam_id="uuid",
        ...     course_id="uuid",
        ...     exam_type="ai_simulation",
        ...     title="IHK FISI AP1 Simulation",
        ...     duration_minutes=90,
        ...     passing_score=50,
        ...     settings={"standard": "IHK_FISI_AP1", "difficulty": "intermediate"},
        ...     questions=[...],
        ...     created_at=datetime.now()
        ... )
    """
    exam_id: str = Field(..., description="Exam UUID")
    course_id: str = Field(..., description="Course UUID")
    exam_type: ExamType = Field(..., description="Type of exam")
    title: str = Field(..., description="Exam title")
    description: Optional[str] = Field(None, description="Exam description")
    duration_minutes: int = Field(default=60, ge=1, description="Exam duration in minutes")
    passing_score: int = Field(default=50, ge=0, le=100, description="Passing score percentage")
    total_points: int = Field(default=100, description="Maximum points achievable")
    settings: Dict[str, Any] = Field(default={}, description="Exam configuration (JSONB)")
    published: bool = Field(default=False, description="Is exam published")
    generated_by_ai: bool = Field(default=False, description="Was generated by AI")
    ai_model: Optional[str] = Field(None, description="AI model used for generation")
    source_modules: List[str] = Field(default=[], description="Source module UUIDs")
    questions: List[ExamQuestionResponse] = Field(default=[], description="Exam questions")
    question_count: int = Field(default=0, description="Total number of questions")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: Optional[datetime] = Field(None, description="Last update timestamp")

    model_config = ConfigDict(from_attributes=True)


class ExamCreateRequest(BaseModel):
    """
    Admin exam creation request model (manual creation)

    Example:
        >>> request = ExamCreateRequest(
        ...     title="Python Basics Test",
        ...     exam_type="practice",
        ...     duration_minutes=60,
        ...     passing_score=70
        ... )
    """
    title: str = Field(..., min_length=3, max_length=255, description="Exam title")
    description: Optional[str] = Field(None, description="Exam description")
    exam_type: ExamType = Field(default=ExamType.PRACTICE, description="Type of exam")
    duration_minutes: int = Field(default=60, ge=5, le=300, description="Exam duration (5-300 minutes)")
    passing_score: int = Field(default=50, ge=0, le=100, description="Passing score percentage")
    total_points: int = Field(default=100, ge=1, description="Maximum points")
    settings: Dict[str, Any] = Field(default={}, description="Additional settings")
    published: bool = Field(default=False, description="Publish immediately")

    model_config = ConfigDict(from_attributes=True)


class ExamUpdateRequest(BaseModel):
    """
    Admin exam update request model

    All fields are optional for partial updates.

    Example:
        >>> update = ExamUpdateRequest(
        ...     title="Updated Title",
        ...     passing_score=60
        ... )
    """
    title: Optional[str] = Field(None, min_length=3, max_length=255, description="Exam title")
    description: Optional[str] = Field(None, description="Exam description")
    duration_minutes: Optional[int] = Field(None, ge=5, le=300, description="Exam duration")
    passing_score: Optional[int] = Field(None, ge=0, le=100, description="Passing score percentage")
    total_points: Optional[int] = Field(None, ge=1, description="Maximum points")
    settings: Optional[Dict[str, Any]] = Field(None, description="Additional settings")
    published: Optional[bool] = Field(None, description="Publish/unpublish")

    model_config = ConfigDict(from_attributes=True)


class ExamGenerateRequest(BaseModel):
    """
    AI exam generation request model

    Based on 09_KI-Pipeline.md:949-1043

    Example:
        >>> request = ExamGenerateRequest(
        ...     title="IHK FISI AP1 Simulation",
        ...     exam_standard="IHK_FISI_AP1",
        ...     difficulty="intermediate",
        ...     duration_minutes=90,
        ...     question_distribution={"mcq": 25, "fill_blanks": 10, "short_answer": 3, "case_study": 2},
        ...     source_module_ids=["uuid1", "uuid2", "uuid3"]
        ... )
    """
    title: str = Field(..., min_length=3, max_length=255, description="Exam title")
    description: Optional[str] = Field(None, description="Exam description")
    exam_standard: ExamStandard = Field(..., description="Exam standard (IHK, CompTIA, etc.)")
    difficulty: str = Field(default="intermediate", description="Difficulty level")
    duration_minutes: int = Field(default=90, ge=30, le=300, description="Exam duration")
    passing_score: int = Field(default=50, ge=0, le=100, description="Passing score percentage")
    total_points: int = Field(default=100, ge=1, description="Maximum points")
    question_distribution: Dict[str, int] = Field(
        ...,
        description="Question type distribution (e.g. {'mcq': 25, 'fill_blanks': 10})"
    )
    topic_coverage: Optional[Dict[str, int]] = Field(
        None,
        description="Topic coverage percentages (e.g. {'netzwerke': 40, 'hardware': 20})"
    )
    source_module_ids: List[str] = Field(
        default=[],
        description="Source module UUIDs to generate from"
    )

    @field_validator('difficulty')
    @classmethod
    def validate_difficulty(cls, v: str) -> str:
        """Validate difficulty level"""
        valid_levels = ['beginner', 'intermediate', 'advanced', 'expert']
        if v not in valid_levels:
            raise ValueError(f'Difficulty must be one of: {", ".join(valid_levels)}')
        return v

    @field_validator('question_distribution')
    @classmethod
    def validate_question_distribution(cls, v: Dict[str, int]) -> Dict[str, int]:
        """Validate question distribution"""
        if not v:
            raise ValueError('question_distribution cannot be empty')

        valid_types = {'mcq', 'true_false', 'fill_blanks', 'matching', 'short_answer', 'math_problem', 'case_study'}
        for qtype in v.keys():
            if qtype not in valid_types:
                raise ValueError(f'Invalid question type: {qtype}. Must be one of: {", ".join(valid_types)}')

        total = sum(v.values())
        if total < 5:
            raise ValueError('Total questions must be at least 5')
        if total > 200:
            raise ValueError('Total questions cannot exceed 200')

        return v

    model_config = ConfigDict(from_attributes=True)
